### ISSUE TITLE
Handle duniter graphical interface

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter_ynh#12]
- [x] [Web-ui sources are not embedded in ARM builds](https://github.com/duniter/duniter/issues/495).
- [x] Manage YunoHost tile:
  - [x] Include it in the nginx conf.
  - [ ] It's not working: #23
- [x] Add nginx redirection from `http://localhost:9220` to `/path`.
- [x] Find an nginx conf `proxy_pass` to access the interface on `/path` and the API on `/path/api`.
- [x] [Fix duniter-ui insecure connection](https://github.com/duniter/duniter/issues/401) using reverse proxy.
- ~~connecting it to the node via:~~
  - ~~`/duniter/api` to access the API using HTTPS, modifying `duniter-ui` conf.~~
  - ~~[`localhost`](https://github.com/duniter/duniter/issues/481).~~
- [x] Restrict `path` installation on `/` for now as [it's not working on subpath `/path`](https://github.com/duniter/duniter_ynh/issues/18):
  - [x] Add `path` check.
  - [x] manifest: don't ask for path, precise at domain asking that it will be installed on `/`
  - [x] install: set and check `$path` == `/`.
- [x] [Manage SSO access](https://github.com/YunoHost/SSOwat#protected_urls):
  - [x] Ask `admin` user (a YunoHost user) at installation.
  - [x] Grant access to `/path` only to the `admin`
  - [ ] Let public access to `/path/api`.
- [x] Add information on credentials asking: `let them as default if you don't have a Duniter account, it is editable with the web admin.`

**Comment by M5oul** [comment]
![capture du 2016-06-17 17-22-46](https://cloud.githubusercontent.com/assets/4758871/16155818/67aa7f78-34b1-11e6-80c8-99431774d88a.png)

I have an error message with many logs errors in web console.

Here is my nginx conf:
```fish
location /duniter/ {
       rewrite                ^/duniter$ /duniter/ permanent;
       proxy_pass             http://localhost:9220/;
       proxy_set_header       Host $host;
       proxy_buffering off;
}
```

**Comment by M5oul** [comment]
It seems the request get SSowed due to CSRF security using this nginx conf file:
```nginx
location /duniter/ {
       proxy_set_header        X-Real-IP       $remote_addr;
       proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header        Host            $host;
       proxy_set_header        X-NgninX-Porxy  true;

       proxy_pass http://localhost:9220;
       proxy_redirect          off;

       # Socket.io support
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
}
```

![capture du 2016-08-08 14-08-11](https://cloud.githubusercontent.com/assets/4758871/17479254/bcce755c-5d71-11e6-9f44-c11bf6df6144.png)


With following nginx conf:
- the request is not SSowed and all files are retrieve
- but, the connection is unsecure
```nginx
location /duniter/ {
       rewrite                ^/duniter$ /duniter/ permanent;
       proxy_pass             http://localhost:9220/;
       proxy_set_header       Host $host;
       proxy_buffering        off;

        location ^~ /duniter/api/ {
              proxy_pass             http://<domain.tld>:8999/;
         }
```
